import React, { useState, useEffect } from 'react'
import clsx from 'clsx'
import type { NextPage } from 'next'
import Head from 'next/head'
import { AwardCategory, SuccessModal } from '../components'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [ballotData, setBallotData] = useState([]);
  const [selectedNominee, setSelectedNominee] = useState({});
  const [openSuccessModal, setOpenSuccessModal] = useState(true);

  useEffect(() => {
    const fetchBallots = async () => {
      const res = await fetch('http://localhost:3000/api/ballots')
      const json = await res.json()

      if(json?.items) {
        setBallotData(json.items)
      }
    };

    fetchBallots();
  },[]);

  const selectItem = (catId: string, catTitle: any, item: any) => {
    setSelectedNominee(
      {
        ...selectedNominee,
        [catId]: {
          catTitle,
          ...item
        }
      }
    )
  };

  const handleSubmitNominations = () => {
    setOpenSuccessModal(true);
  };

  return (
    <div className={clsx(styles.container, openSuccessModal && styles.modalOpen)}>
      <Head>
        <title>Movie Awards 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' />
      </Head>

      <main className={styles.main}>
        <h1> Movie Awards 2021 </h1>
        {
          ballotData.map(category => {
            const { id = '' } = category

            return (
              <AwardCategory
                key={id}
                data={category}
                selectItem={selectItem}
                selectedValue={selectedNominee}
              />
            );
          })
        }
        <button
          className={styles.submitButton}
          onClick={handleSubmitNominations}
        >
          Submit Nominations
        </button>
      </main>

      {
        openSuccessModal &&
          <SuccessModal
            data={selectedNominee}
            closePopup={ () => setOpenSuccessModal(false) }
          />
      }
    </div>
  )
}


export default Home
